### ISSUE TITLE
Correct spelling

### ISSUE THREAD

**Issue by ligi** [walleth/walleth.github.com#2]
This is mainly to honor @stevesbrain for https://github.com/walleth/walleth.github.com/pull/1

**Comment by ligi** [comment]
blocked by https://github.com/issuETH/issuETH/issues/9

**Comment by stevesbrain** [comment]
@ligi Not sure exactly how the bot works (and based on what you've said, it can't work due to me not being a member anyway - that is, if this was ever actually intended for me, and not just testing :stuck_out_tongue: ), but glad I could help out (even if in a minor way) all the same :)
