### ISSUE TITLE
PLEASE HELP 

### ISSUE THREAD

**Issue by gwap0ako025** [walleth/walleth.github.com#3]
![IMG_20200411_054335](https://user-images.githubusercontent.com/62929119/79026954-fd2eeb00-7bbc-11ea-9135-644897ce114c.jpg)

I MADE JUST RECIEVE ETH HOW COME THIS WAS NOT CREDITED ?

**Comment by ligi** [comment]
can you send me your address so I can have a look?

**Comment by gwap0ako025** [comment]
Here's my wallet address

**Comment by ligi** [comment]
where?

**Comment by ligi** [comment]
withouth info I cannot help
