### ISSUE TITLE
Fix logo font

### ISSUE THREAD

**Issue by ligi** [walleth/walleth.github.com#4]
Somehow on the deployed version the font is weird - should look like this:

![Selection_032](https://user-images.githubusercontent.com/111600/111087118-0b4d6000-8520-11eb-8672-978932bde73d.png)

but looks like this:

![Selection_033](https://user-images.githubusercontent.com/111600/111087142-291ac500-8520-11eb-93ae-ae383baca7bd.png)

**Comment by 0xdeadf4ce** [comment]
https://twitter.com/0xdeadf4ce/status/1371233956440465408?s=20 👀
